### ISSUE TITLE
Database Models

### ISSUE THREAD

**Issue by ybira** [flowacademyhu/presence-manager-server#2]
## Leírás

- A feladat a user model elkészítése és bekonfigurálása, hogy a controllereken keresztül hívható és módosítható legyen.
- **username: String - kötelező** -> a felhasználó által választott felhasználónév, belépéshez
- **password: String - kötelező** -> elhashelt jelszó, belépéshez
- **email: String - kötelező** -> a felhasználó email címét tartalmazó mező célja az azonosítás
- **contractId: String - kötelező** -> a felhasználó azonosításához, egyelőre kötelezőként, amennyiben a meetupokra is bevezetésre kerül akkor nem lehet kötelező
- **authenticationLevel: Integer - kötelező** -> hozzáférési szint
- **logs: String[]** -> be illetve kilépési adatokat tartalmazó lista
- **isIn: Boolean** -> átbillenthető boolean arra, hogy gyorsan kikereshető legyen kik vannak bent

## Elvárások

- [x] Modelt tartalmazó JS fájl elkészítése 
- [x] Robo 3T-n keresztüli tesztelése (egyszerű beillesztés, lekérdezés)

**Comment by VarGabor87** [comment]
Javítottam. Mentor, Visitor, TeamGamma, TeamDelta elérhető.
